import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GalleryLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header
        pageTitle="Gallery"
        keywords={["Festival", "Downloads", "Files", "Forms", "Criteria"]}
      />
      <main>{children}</main>
    </>
  );
}
